[user]
name = "Julien Vincent"
email = "m@julienvincent.io"

[ui]
default-command = "log-reversed"
diff-instructions = false
paginate = "never"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[aliases]
log-reversed = ["log", "--reversed"]

fetch = ["git", "fetch"]
push = ["git", "push"]

[git]
auto-local-branch = true
push-branch-prefix = "jv/change-"

[signing]
sign-all = true
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFrtvt1/rcCsF7Jf4zgmu/vjRnzEXMlXzt8FmouxCxFH"
backend = "ssh"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"
backends.ssh.allowed-signers = "/Users/julienvincent/.ssh/allowed-signers"

[colors]
current = { fg = "yellow", bg = "black", bold = true, underline = true }

[revset-aliases]

'local()' = 'trunk()..mine()'

[revsets]

log = 'trunk()..@ | trunk() | @:: | @-::'
