"$schema" = "https://jj-vcs.github.io/jj/v0.34.0/config-schema.json"

[user]
name = "Julien Vincent"
email = "m@julienvincent.io"

[ui]
default-command = "logr"
diff-instructions = false

diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

# This is wrapped in 'sh -c' so that I can expand the $HOME env var
pager = ["sh", "-c", "delta --config $HOME/.config/delta/config.ini"]
diff-formatter = ":git"

[merge-tools.dt]
program = "difft"
diff-args = [
  "--color=always",
  "--tab-width=2",
  "--display=side-by-side",
  "$left",
  "$right",
]

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
    "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

[aliases]
logr = ["log", "--reversed"]

log-oneline = ["log", "-T", "log_oneline_compact", "--no-graph"]
l = ["log-oneline", "-r", "::@ & ~merges()"]

fetch = ["git", "fetch"]
push = ["git", "push"]

changelog = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
jj log --reversed -Tchangelog --no-graph -r "$@ & ~merges()"
""", ""]

[git]
push-new-bookmarks = true
write-change-id-header = true
colocate = true

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFrtvt1/rcCsF7Jf4zgmu/vjRnzEXMlXzt8FmouxCxFH"
backends.ssh.allowed-signers = "~/.ssh/allowed-signers"

[colors]
current = { fg = "yellow", bg = "black", bold = true, underline = true }

[revset-aliases]

'stack(tip)' = "fork_point(trunk():: | tip)::tip | trunk() | tip-::"
'expand(tip)' = "fork_point(trunk():: | tip):: | tip"
'find(from, to)' = "fork_point(to:: | from)::from | fork_point(to:: | from)::to"

local = 'trunk()..mine()'
expand = "expand(@)"

[revsets]

log = "stack(@)"

[templates]
git_push_bookmark = '"jv/ref-" ++ change_id.short()'

[template-aliases]
'format_as_date(timestamp)' = 'timestamp.local().format("%Y-%m-%d")'

'format_as_datetime(timestamp)' = 'timestamp.local().format("%Y-%m-%d %H:%M:%S")'
'format_timestamp(timestamp)' = 'timestamp.ago()'

log_oneline_compact = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        format_short_commit_id(commit_id),
        pad_end(10, truncate_end(10, author.email())),
        pad_start(12, format_timestamp(commit_timestamp(self))),
        bookmarks,
        tags,
        working_copies,
        if(git_head, label("git_head", "git_head()")),
        if(conflict, label("conflict", "conflict")),
        if(config("ui.show-cryptographic-signatures").as_boolean(),
          format_short_cryptographic_signature(signature)),
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''

# Use with:
# jj changelog -r v0.3.0::master
changelog = '''
"+ **" ++ description.first_line() ++ "** in " ++ format_short_commit_id(commit_id) ++ "\n" ++
  if(description.remove_prefix(description.first_line()).trim_start(),
    indent("  ", "> " ++ description.remove_prefix(description.first_line()).trim_start().lines().join("\n> ")) ++ "\n",
    "")
'''
