[user]
name = "Julien Vincent"
email = "m@julienvincent.io"

[ui]
default-command = "logr"
diff-instructions = false

diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

# This is wrapped in 'sh -c' so that I can expand the $HOME env var
pager = ["sh", "-c", "delta --config $HOME/.config/delta/config.ini"]
diff.format = "git"

[merge-tools.dt]
program = "difft"
diff-args = [
  "--color=always",
  "--tab-width=2",
  "--display=side-by-side",
  "$left",
  "$right",
]


[aliases]
logr = ["log", "--reversed"]

log-oneline = ["log", "-T", "builtin_log_oneline", "--no-graph"]
l = ["log-oneline", "-r", "::@"]

fetch = ["git", "fetch"]
push = ["git", "push"]

[git]
auto-local-bookmark = true
push-bookmark-prefix = "jv/ref-"
push-new-bookmarks = true

[signing]
sign-all = true
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFrtvt1/rcCsF7Jf4zgmu/vjRnzEXMlXzt8FmouxCxFH"
backends.ssh.allowed-signers = "~/.ssh/allowed-signers"

[colors]
current = { fg = "yellow", bg = "black", bold = true, underline = true }

[revset-aliases]

'local()' = 'trunk()..mine()'

[revsets]

log = "fork_point(trunk():: | @)::@ | trunk()"
