"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# A minimal left prompt
format = """
$directory\
$cmd_duration\
${custom.jujutsu}\
$fill \
$kubernetes\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$status\
$container\
$shell\
$time\
$character"""

[fill]
symbol = "-"
style = "black"

[directory]
truncate_to_repo = false
style = "bright-yellow"
truncation_length = 8

[gcloud]
disabled = true

[package]
disabled = true

[nodejs]
format = "[$symbol($version )]($style)"
style = "bright-green"

[kubernetes]
disabled = false
style = "bright-purple"
format = "[$symbol$context]($style) "

[custom.jujutsu]
detect_folders = [".jj"]
shell=["sh"]
command="~/.config/starship/jujutsu.sh"
