[tools]
clojure = "1.12.4.1618"
rust-analyzer = "2026-01-26"
rust = "nightly-2026-01-21"
java = "temurin-25.0.2+10.0.LTS"
go = "1.22.0"
python = "3.11.3"
maven = "3.9.1"
node = "25.6.0"
neovim = "0.12.1"
kubectl = "1.32.2"
kubectx = "0.9.5"
taplo = "0.10.0"
atuin = "18.13.3"
prettier = "3.8.1"
doggo = "1.1.4"
zig = "0.15.2"
gron = "0.7.1"
stern = "1.33.1"
opencode = "1.14.39"
deno = "2.7.6"

[tool_alias.java.versions]
graal = 'graalvm-community-25.0.2'

[settings]
idiomatic_version_file_enable_tools = ["node"]
