general {
  lock_cmd = pidof hyprlock || hyprlock

  before_sleep_cmd = loginctl lock-session && bluetoothctl power off
  after_sleep_cmd = $XDG_CONFIG_HOME/hypr/scripts/enable-monitors.sh && bluetoothctl power on
}

listener {
  # 4 min
  timeout = 240
  on-timeout = brightnessctl -s set 10
  on-resume = brightnessctl -r
}

listener {
  # 5 min
  timeout = 300
  on-timeout = loginctl lock-session
}

listener {
  # 5.5 min
  timeout = 330
  on-timeout = $XDG_CONFIG_HOME/hypr/scripts/disable-monitors.sh
  on-resume = $XDG_CONFIG_HOME/hypr/scripts/enable-monitors.sh && brightnessctl -r
}

listener {
  timeout = 10
  on-timeout = pgrep -x hyprlock && $XDG_CONFIG_HOME/hypr/scripts/disable-monitors.sh
  on-resume  = pgrep -x hyprlock && $XDG_CONFIG_HOME/hypr/scripts/enable-monitors.sh && brightnessctl -r
}

# I am having significant issues with suspend in general on Asahi, so I am only
# going to suspend if on battery power.
listener {
  # 30 min
  timeout = 1800 
  on-timeout = upower -b | grep 'state:.*discharging' && systemctl suspend
}
