source = ~/.config/hypr/hyperland/monitors.conf
source = ~/.config/hypr/hyperland/compat.conf

# Add flatpak installs to XDG so that they show up in quickshell
env = XDG_DATA_DIRS,$XDG_DATA_DIRS:/var/lib/flatpak/exports/share
env = PATH,$HOME/.local/bin:$XDG_CONFIG_HOME/hypr/bin:$PATH

exec-once = hyprsunset
exec-once = hyprpaper
exec-once = hypridle
exec-once = quickshell
exec-once = wl-paste --watch cliphist store
exec-once = hyprpm reload

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

source = ~/.config/hypr/hyperland/ui.conf
source = ~/.config/hypr/hyperland/input.conf

# Keybinds
source = ~/.config/hypr/hyperland/keybinds/general.conf
source = ~/.config/hypr/hyperland/keybinds/workspace.conf
source = ~/.config/hypr/hyperland/keybinds/window.conf
source = ~/.config/hypr/hyperland/keybinds/apps.conf
source = ~/.config/hypr/hyperland/keybinds/terminal.conf

# Rules
source = ~/.config/hypr/hyperland/rules/airplay.conf
source = ~/.config/hypr/hyperland/rules/localsend.conf

# Ignore maximize requests from apps
windowrule = suppressevent maximize, class:.*
