sync_address = "https://atuin.julienvincent.io"

dialect = "uk"
style = "compact"
inline_height = 0
show_preview = true
show_help = false
show_tabs = false

enter_accept = false
search_mode_shell_up_key_binding = "prefix"

keymap_cursor = { emacs = "steady-underline", vim_insert = "steady-underline", vim_normal = "steady-block" }
