# General

bind = SUPER SHIFT, P, exec, 1password --quick-access

windowrule {
  name = onepassword-quick-access
  match:class = ^(.*1password.*)$
  match:initial_title = 1Password

  float = on
  center = on
  size = 40% 40%
  stay_focused = on
}

# === TUIs

# Numr Override
windowrule = size 30% 40%, match:class ^(local\.tui\.numr).*$

bind = SUPER SHIFT, C, exec, focus-tui numr

# Standard

windowrule {
  name = standard-tuis
  match:class = ^(local\.tui).*$

  float = on
  center = on
  size = 70% 75%
  stay_focused = on
}

bind = SUPER SHIFT, K, exec, focus-tui btm
bind = SUPER SHIFT, B, exec, focus-tui bluetui
bind = SUPER SHIFT, A, exec, focus-tui wiremix
bind = SUPER SHIFT, L, exec, focus-tui yazi

# ===

windowrule = size 1000 700, match:float true, match:initial_class zen

windowrule = float on, match:class org.freedesktop.impl.portal.desktop.kde
windowrule = size 1200 900, match:class org.freedesktop.impl.portal.desktop.kde
