# Quake Term
windowrulev2 = bordercolor rgba(ff0000ff), workspace:special:quaketerm
windowrulev2 = bordersize 10, workspace:special:quaketerm
workspace = special:quaketerm, on-created-empty:ghostty +new-window

bind = CTRL, grave, togglespecialworkspace, quaketerm

