windowrule {
  name = quaketerm
  match:workspace = special:quaketerm

  border_color = rgb(d65d0e)
  border_size = 4
}
workspace = special:quaketerm, on-created-empty:ghostty +new-window

bind = CTRL, grave, togglespecialworkspace, quaketerm
