# == Workspace Management Submap

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# ==

# Groups
bind = SUPER, G, togglegroup,
bind = SUPER SHIFT, period, moveintogroup, r
bind = SUPER SHIFT, comma, moveintogroup, l

bind = SUPER ALT, period, changegroupactive, f
bind = SUPER ALT, comma, changegroupactive, b

# Switch workspaces
bind = SUPER, 1, exec, switch-workspace 1
bind = SUPER, 2, exec, switch-workspace 2
bind = SUPER, 3, exec, switch-workspace 3
bind = SUPER, 4, exec, switch-workspace 4
bind = SUPER, 5, exec, switch-workspace 5
bind = SUPER, 6, exec, switch-workspace 6
bind = SUPER, 7, exec, switch-workspace 7
bind = SUPER, 8, exec, switch-workspace 8
bind = SUPER, 9, exec, switch-workspace 9
bind = SUPER, 0, exec, switch-workspace 10

# Cycle workspaces
bind = SUPER ALT CTRL, comma, workspace, -1
bind = SUPER ALT CTRL, period, workspace, +1

# Move workspace between monitors
bind = CTRL ALT, left, movecurrentworkspacetomonitor, l
bind = CTRL ALT, right, movecurrentworkspacetomonitor, r
