require("hyperland.rules.airplay")
require("hyperland.rules.dolphin")
require("hyperland.rules.kde-portal")
require("hyperland.rules.localsend")
require("hyperland.rules.zen")
require("hyperland.rules.kicad")
require("hyperland.rules.feh")
